# Klein Nut Driver Caddy - Base Platform with Handle
# Proposed Revision 1.3
#
# This revision extends the proven Revision 1.2 base-plate architecture.
# It creates one manufacturable body with:
#   - 8.000 in overall width
#   - 9.500 in overall height
#   - 0.375 in thickness
#   - 0.500 in outside plan-view corner radius
#   - 4.000 x 1.000 in integrated rounded-rectangle handle opening
#   - 0.500 in top margin
#
# No mounting holes or shaft cradles are included.
#
# IMPORTANT WORKFLOW NOTE:
# Keep Revision 1.2 committed in Git before adopting this file. This proposed
# revision intentionally retains the existing body name so downstream work can
# continue to reference a stable generated body name.
#
# Fusion 360 API dimensions are internally stored in centimeters, but all
# controlling dimensions below are Fusion user parameters expressed in inches.

import adsk.core
import adsk.fusion
import traceback


SCRIPT_NAME = 'Klein Nut Driver Caddy - Base Platform Rev 1.3'
BODY_NAME = 'Klein Nut Driver Caddy Base Platform'

OUTER_SKETCH_NAME = 'Klein Caddy Base Platform Footprint'
HANDLE_SKETCH_NAME = 'Klein Caddy Handle Opening'


def get_or_create_parameter(design, name, expression, units, comment):
    """Create a Fusion user parameter, or update its expression and comment."""
    user_params = design.userParameters
    parameter = user_params.itemByName(name)

    if parameter:
        parameter.expression = expression
        parameter.comment = comment
        return parameter

    return user_params.add(
        name,
        adsk.core.ValueInput.createByString(expression),
        units,
        comment
    )


def create_user_parameters(design):
    """Create all parameters required by the base platform and handle."""
    specifications = (
        (
            'BoardWidth',
            '8.000 in',
            'in',
            'Overall width of the nut-driver caddy base platform.'
        ),
        (
            'BoardHeight',
            '9.500 in',
            'in',
            'Overall height of the nut-driver caddy base platform.'
        ),
        (
            'BoardThickness',
            '0.375 in',
            'in',
            'Uniform base-platform thickness.'
        ),
        (
            'CornerRadius',
            '0.500 in',
            'in',
            'Plan-view radius of the four outside platform corners.'
        ),
        (
            'HandleWidth',
            '4.000 in',
            'in',
            'Overall width of the integrated handle opening.'
        ),
        (
            'HandleHeight',
            '1.000 in',
            'in',
            'Overall height of the integrated handle opening.'
        ),
        (
            'HandleTopMargin',
            '0.500 in',
            'in',
            'Material remaining between the handle opening and top edge.'
        ),
        (
            'HandleCornerRadius',
            '0.500 in',
            'in',
            'Plan-view radius at each handle-opening corner.'
        ),
    )

    for name, expression, units, comment in specifications:
        get_or_create_parameter(
            design,
            name,
            expression,
            units,
            comment
        )


def delete_existing_generated_body(root_component):
    """
    Delete only a body generated by this revision.

    This does not delete unrelated bodies. The prior source revision should
    remain protected by Git history before this revision is adopted.
    """
    generated_names = {
        BODY_NAME,
        'Klein Nut Driver Caddy Base Plate',
    }

    for index in range(root_component.bRepBodies.count - 1, -1, -1):
        body = root_component.bRepBodies.item(index)
        if body.name in generated_names:
            body.deleteMe()


def identify_rectangle_axis_lines(rectangle_lines):
    """Return one horizontal and one vertical line from a sketch rectangle."""
    horizontal_line = None
    vertical_line = None

    for line in rectangle_lines:
        start = line.startSketchPoint.geometry
        end = line.endSketchPoint.geometry

        dx = abs(end.x - start.x)
        dy = abs(end.y - start.y)

        if dx > dy and horizontal_line is None:
            horizontal_line = line
        elif dy > dx and vertical_line is None:
            vertical_line = line

    if not horizontal_line or not vertical_line:
        raise RuntimeError(
            'Could not identify horizontal and vertical rectangle lines.'
        )

    return horizontal_line, vertical_line


def add_outer_footprint_sketch(root_component):
    """Create the centered, dimension-driven outer platform footprint."""
    sketch = root_component.sketches.add(
        root_component.xYConstructionPlane
    )
    sketch.name = OUTER_SKETCH_NAME

    lines = sketch.sketchCurves.sketchLines

    # Temporary 8.000 x 9.500 in rectangle in Fusion internal centimeters.
    center = adsk.core.Point3D.create(0, 0, 0)
    corner = adsk.core.Point3D.create(10.16, 12.065, 0)

    rectangle_lines = lines.addCenterPointRectangle(center, corner)
    horizontal_line, vertical_line = identify_rectangle_axis_lines(
        rectangle_lines
    )

    dimensions = sketch.sketchDimensions

    width_dimension = dimensions.addDistanceDimension(
        horizontal_line.startSketchPoint,
        horizontal_line.endSketchPoint,
        adsk.fusion.DimensionOrientations.HorizontalDimensionOrientation,
        adsk.core.Point3D.create(0, -13.5, 0)
    )
    width_dimension.parameter.expression = 'BoardWidth'

    height_dimension = dimensions.addDistanceDimension(
        vertical_line.startSketchPoint,
        vertical_line.endSketchPoint,
        adsk.fusion.DimensionOrientations.VerticalDimensionOrientation,
        adsk.core.Point3D.create(-11.5, 0, 0)
    )
    height_dimension.parameter.expression = 'BoardHeight'

    if sketch.profiles.count != 1:
        raise RuntimeError(
            'Outer footprint must contain exactly one closed profile; '
            f'found {sketch.profiles.count}.'
        )

    return sketch


def extrude_base_platform(root_component, footprint_sketch):
    """Extrude the outer footprint into one new solid body."""
    extrudes = root_component.features.extrudeFeatures

    extrude_input = extrudes.createInput(
        footprint_sketch.profiles.item(0),
        adsk.fusion.FeatureOperations.NewBodyFeatureOperation
    )
    extrude_input.setDistanceExtent(
        False,
        adsk.core.ValueInput.createByString('BoardThickness')
    )

    extrusion = extrudes.add(extrude_input)
    extrusion.name = 'Klein Caddy Base Platform Extrusion'

    body = extrusion.bodies.item(0)
    body.name = BODY_NAME
    return body


def collect_vertical_straight_edges(body):
    """
    Collect straight edges parallel to the Z axis.

    Vertex-coordinate comparison is used because Line3D.direction is not
    consistently available across Fusion API versions.
    """
    vertical_edges = adsk.core.ObjectCollection.create()
    tolerance = 0.0001

    for edge in body.edges:
        start_vertex = edge.startVertex
        end_vertex = edge.endVertex

        if not start_vertex or not end_vertex:
            continue

        start = start_vertex.geometry
        end = end_vertex.geometry

        same_x = abs(start.x - end.x) < tolerance
        same_y = abs(start.y - end.y) < tolerance
        different_z = abs(start.z - end.z) > tolerance

        if same_x and same_y and different_z:
            vertical_edges.add(edge)

    return vertical_edges


def add_constant_radius_fillet(root_component, edges, radius_expression, name):
    """Apply one constant-radius fillet feature to the supplied edge set."""
    fillets = root_component.features.filletFeatures
    fillet_input = fillets.createInput()

    fillet_input.edgeSetInputs.addConstantRadiusEdgeSet(
        edges,
        adsk.core.ValueInput.createByString(radius_expression),
        True
    )

    feature = fillets.add(fillet_input)
    feature.name = name
    return feature


def round_outer_corners(root_component, body):
    """Apply the specified plan-view radius to the four outside corners."""
    vertical_edges = collect_vertical_straight_edges(body)

    if vertical_edges.count != 4:
        raise RuntimeError(
            'Expected four outside vertical edges before corner rounding; '
            f'found {vertical_edges.count}.'
        )

    add_constant_radius_fillet(
        root_component,
        vertical_edges,
        'CornerRadius',
        'Klein Caddy Outside Corner Radius'
    )


def find_top_planar_face(body):
    """Return the planar face having the greatest Z-coordinate."""
    top_face = None
    top_z = None

    for face in body.faces:
        plane = adsk.core.Plane.cast(face.geometry)
        if not plane:
            continue

        z_value = face.pointOnFace.z
        if top_face is None or z_value > top_z:
            top_face = face
            top_z = z_value

    if not top_face:
        raise RuntimeError('Unable to identify the top planar platform face.')

    return top_face


def add_handle_sketch(root_component, body):
    """
    Create a fully dimension-driven rectangular handle profile.

    The profile is initially rectangular. The four vertical cut edges are
    filleted after the through-cut, creating a robust rounded rectangle while
    keeping the sketch and feature sequence simple and stable.
    """
    top_face = find_top_planar_face(body)
    sketch = root_component.sketches.add(top_face)
    sketch.name = HANDLE_SKETCH_NAME

    lines = sketch.sketchCurves.sketchLines

    # Temporary points for the confirmed 4.000 x 1.000 in opening.
    # Board coordinates are centered at the origin:
    # top edge = +4.750 in; handle top = +4.250 in.
    # With a 1.000 in opening height, handle bottom = +3.250 in.
    top_left = adsk.core.Point3D.create(-5.08, 10.795, 0)
    bottom_right = adsk.core.Point3D.create(5.08, 8.255, 0)

    rectangle_lines = lines.addTwoPointRectangle(top_left, bottom_right)

    top_line = None
    side_line = None
    top_left_point = None

    for line in rectangle_lines:
        start = line.startSketchPoint.geometry
        end = line.endSketchPoint.geometry
        dx = abs(end.x - start.x)
        dy = abs(end.y - start.y)

        if dx > dy:
            line_y = (start.y + end.y) / 2.0
            if top_line is None:
                top_line = line
            else:
                current_y = (
                    top_line.startSketchPoint.geometry.y +
                    top_line.endSketchPoint.geometry.y
                ) / 2.0
                if line_y > current_y:
                    top_line = line
        elif side_line is None:
            side_line = line

    if not top_line or not side_line:
        raise RuntimeError('Could not identify handle rectangle lines.')

    # Identify the left endpoint of the top line.
    if (
        top_line.startSketchPoint.geometry.x <
        top_line.endSketchPoint.geometry.x
    ):
        top_left_point = top_line.startSketchPoint
    else:
        top_left_point = top_line.endSketchPoint

    dimensions = sketch.sketchDimensions

    width_dimension = dimensions.addDistanceDimension(
        top_line.startSketchPoint,
        top_line.endSketchPoint,
        adsk.fusion.DimensionOrientations.HorizontalDimensionOrientation,
        adsk.core.Point3D.create(0, 11.7, 0)
    )
    width_dimension.parameter.expression = 'HandleWidth'

    height_dimension = dimensions.addDistanceDimension(
        side_line.startSketchPoint,
        side_line.endSketchPoint,
        adsk.fusion.DimensionOrientations.VerticalDimensionOrientation,
        adsk.core.Point3D.create(-6.2, 8.2, 0)
    )
    height_dimension.parameter.expression = 'HandleHeight'

    # Horizontally center the opening on the board origin.
    x_location_dimension = dimensions.addDistanceDimension(
        sketch.originPoint,
        top_left_point,
        adsk.fusion.DimensionOrientations.HorizontalDimensionOrientation,
        adsk.core.Point3D.create(-3.0, 0, 0)
    )
    x_location_dimension.parameter.expression = 'HandleWidth / 2'

    # Locate the handle top edge from the centered board origin.
    y_location_dimension = dimensions.addDistanceDimension(
        sketch.originPoint,
        top_left_point,
        adsk.fusion.DimensionOrientations.VerticalDimensionOrientation,
        adsk.core.Point3D.create(0, 8.0, 0)
    )
    y_location_dimension.parameter.expression = (
        'BoardHeight / 2 - HandleTopMargin'
    )

    if sketch.profiles.count < 1:
        raise RuntimeError(
            'Handle sketch did not produce a closed profile.'
        )

    return sketch


def get_smallest_profile(sketch):
    """
    Return the smallest closed profile in a sketch.

    A sketch created directly on a planar body face can include both the
    platform face boundary and the newly drawn handle boundary. The handle
    opening is the smaller enclosed profile.
    """
    if sketch.profiles.count < 1:
        raise RuntimeError('Sketch contains no closed profiles.')

    smallest_profile = None
    smallest_area = None

    for index in range(sketch.profiles.count):
        profile = sketch.profiles.item(index)
        area = profile.areaProperties().area

        if smallest_profile is None or area < smallest_area:
            smallest_profile = profile
            smallest_area = area

    return smallest_profile


def cut_handle_opening(root_component, handle_sketch):
    """Cut the smaller internal handle profile through the platform body."""
    extrudes = root_component.features.extrudeFeatures
    handle_profile = get_smallest_profile(handle_sketch)

    cut_input = extrudes.createInput(
        handle_profile,
        adsk.fusion.FeatureOperations.CutFeatureOperation
    )
    cut_input.setAllExtent(
        adsk.fusion.ExtentDirections.NegativeExtentDirection
    )

    cut_feature = extrudes.add(cut_input)
    cut_feature.name = 'Klein Caddy Handle Through Cut'
    return cut_feature


def collect_handle_corner_edges(design, body):
    """
    Return only the four vertical edges belonging to the handle cutout.

    The outside corner fillets create additional vertical edges, so the
    handle edges are identified by their XY position within the handle region.
    """
    parameters = design.userParameters

    board_height = parameters.itemByName('BoardHeight').value
    handle_width = parameters.itemByName('HandleWidth').value
    handle_height = parameters.itemByName('HandleHeight').value
    top_margin = parameters.itemByName('HandleTopMargin').value

    half_handle_width = handle_width / 2.0
    handle_top = board_height / 2.0 - top_margin
    handle_bottom = handle_top - handle_height

    # Fusion stores model coordinates internally in centimeters.
    tolerance = 0.01
    selected_edges = adsk.core.ObjectCollection.create()

    for edge in body.edges:
        start_vertex = edge.startVertex
        end_vertex = edge.endVertex

        if not start_vertex or not end_vertex:
            continue

        start = start_vertex.geometry
        end = end_vertex.geometry

        is_vertical = (
            abs(start.x - end.x) < tolerance and
            abs(start.y - end.y) < tolerance and
            abs(start.z - end.z) > tolerance
        )

        if not is_vertical:
            continue

        midpoint_x = (start.x + end.x) / 2.0
        midpoint_y = (start.y + end.y) / 2.0

        inside_handle_width = (
            abs(midpoint_x) <= half_handle_width + tolerance
        )
        inside_handle_height = (
            handle_bottom - tolerance <= midpoint_y <= handle_top + tolerance
        )

        if inside_handle_width and inside_handle_height:
            selected_edges.add(edge)

    return selected_edges


def round_handle_opening(root_component, design, body):
    """Apply the radius to the four internal handle-opening corners."""
    handle_edges = collect_handle_corner_edges(design, body)

    if handle_edges.count != 4:
        raise RuntimeError(
            'Unable to isolate the four handle corner edges; '
            f'found {handle_edges.count}.'
        )

    add_constant_radius_fillet(
        root_component,
        handle_edges,
        'HandleCornerRadius',
        'Klein Caddy Handle Corner Radius'
    )

def validate_parameter_proportions(design):
    """Reject parameter combinations that cannot produce valid geometry."""
    units = design.unitsManager

    def value(expression):
        return units.evaluateExpression(expression, 'in')

    board_width = value('BoardWidth')
    board_height = value('BoardHeight')
    corner_radius = value('CornerRadius')
    handle_width = value('HandleWidth')
    handle_height = value('HandleHeight')
    handle_margin = value('HandleTopMargin')
    handle_radius = value('HandleCornerRadius')

    if board_width <= 0 or board_height <= 0:
        raise ValueError('BoardWidth and BoardHeight must be positive.')

    if corner_radius <= 0:
        raise ValueError('CornerRadius must be positive.')

    if 2.0 * corner_radius >= min(board_width, board_height):
        raise ValueError(
            'CornerRadius is too large for the selected board dimensions.'
        )

    if handle_width <= 0 or handle_height <= 0:
        raise ValueError('HandleWidth and HandleHeight must be positive.')

    if handle_width >= board_width:
        raise ValueError('HandleWidth must be smaller than BoardWidth.')

    if handle_height + handle_margin >= board_height:
        raise ValueError(
            'HandleHeight plus HandleTopMargin must be less than BoardHeight.'
        )

    if handle_radius <= 0:
        raise ValueError('HandleCornerRadius must be positive.')

    if 2.0 * handle_radius > min(handle_width, handle_height):
        raise ValueError(
            'HandleCornerRadius cannot exceed half the smaller handle size.'
        )


def create_base_platform(root_component, design):
    """Build the complete base platform as one printable solid body."""
    create_user_parameters(design)
    validate_parameter_proportions(design)

    delete_existing_generated_body(root_component)

    footprint_sketch = add_outer_footprint_sketch(root_component)
    body = extrude_base_platform(root_component, footprint_sketch)

    round_outer_corners(root_component, body)

    handle_sketch = add_handle_sketch(root_component, body)
    cut_handle_opening(root_component, handle_sketch)
    round_handle_opening(root_component, design, body)

    return body


def run(context):
    app = None
    ui = None

    try:
        app = adsk.core.Application.get()
        ui = app.userInterface

        design = adsk.fusion.Design.cast(app.activeProduct)

        if not design:
            app.documents.add(
                adsk.core.DocumentTypes.FusionDesignDocumentType
            )
            design = adsk.fusion.Design.cast(app.activeProduct)

        if not design:
            raise RuntimeError(
                'Unable to create or access a Fusion design.'
            )

        create_base_platform(design.rootComponent, design)
        app.activeViewport.fit()

        ui.messageBox(
            'Base Platform Revision 1.3 created successfully.\n\n'
            'Overall size: 8.000 x 9.500 x 0.375 in\n'
            'Outside corner radius: 0.500 in\n'
            'Handle opening: 4.000 x 1.000 in\n'
            'Handle top margin: 0.500 in\n'
            'Handle corner radius: 0.500 in\n\n'
            'No mounting holes or shaft cradles were added.\n\n'
            'Parameters are available under:\n'
            'Modify > Change Parameters',
            SCRIPT_NAME
        )

    except:
        if ui:
            ui.messageBox(
                'The script failed:\n\n{}'.format(
                    traceback.format_exc()
                ),
                SCRIPT_NAME
            )
